ticket9796 : Create form for create/update question
N-Viet-ruby-dev/question-answer-v2 pull request #10
Opened 2019-04-17 07:55 UTC by manh11117

2019-04-18 09:10 UTC, N-Viet-ruby-dev approved these changes

2019-04-18 09:10 UTC, N-Viet-ruby-dev commented on app/controllers/admin/questions_controller.rb
> +      check_box
Hàm này để làm gì?

2019-04-18 09:10 UTC, N-Viet-ruby-dev commented on app/controllers/admin/questions_controller.rb
> +      check_box
Hàm này để làm gì?

2019-04-18 09:13 UTC, manh11117 commented on app/controllers/admin/questions_controller.rb
> +      check_box
để đếm số tick vào check box

2019-04-18 09:24 UTC, N-Viet-ruby-dev commented on app/controllers/admin/questions_controller.rb
> +      check_box
không cần cái này, chỉ cần validate đúng trong model là được

2019-04-18 09:32 UTC, N-Viet-ruby-dev requested changes

2019-04-18 09:32 UTC, N-Viet-ruby-dev commented on app/views/admin/questions/edit.html.erb
> +<h1>Sửa câu hỏi</h1>
Dùng tiếng Anh

2019-04-18 11:42 UTC, N-Viet-ruby-dev commented on app/controllers/admin/questions_controller.rb
> +    # http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]
Bỏ dòng này đi thì bị lỗi rubocop gì?

2019-04-18 11:43 UTC, N-Viet-ruby-dev commented on app/validators/answer_validator.rb
> +    record.errors[attribute] << adderror unless flag_count <= 1 && @i <= 1
chỉ cần một biến để count

2019-04-18 14:03 UTC, manh11117 commented on app/controllers/admin/questions_controller.rb
> +    # http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]
không bị gì cái này ở trong rails getting stated em cop vào cho nhanh ấy mà

2019-04-19 08:30 UTC, N-Viet-ruby-dev approved these changes

2019-04-19 08:30 UTC, merged