Ticket9695
N-Viet-ruby-dev/question-answer-v2 pull request #2
Opened 2019-04-01 07:37 UTC by manh11117

2019-04-01 07:43 UTC, N-Viet-ruby-dev commented
Sửa lại danh sách các commit

2019-04-01 07:43 UTC, N-Viet-ruby-dev commented on test/fixtures/users.yml
> +# Read about fixtures at http://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
bỏ qua phần test

2019-04-01 07:43 UTC, N-Viet-ruby-dev commented
Thêm model

2019-04-01 07:47 UTC, N-Viet-ruby-dev requested changes

2019-04-01 07:47 UTC, N-Viet-ruby-dev commented on db/migrate/20190401071857_create_users.rb
> +      t.string :reset_password_token, index: true, name: "index_users_on_reset_password_token", unique: true
Cái này để làm gì? Nếu không dùng xóa đi

2019-04-01 07:47 UTC, N-Viet-ruby-dev commented on db/migrate/20190401071857_create_users.rb
> +      t.datetime :reset_password_sent_at
Cái này để làm gì? Nếu không dùng xóa đi

2019-04-01 07:47 UTC, N-Viet-ruby-dev commented on db/migrate/20190401071857_create_users.rb
> +      t.datetime :remember_created_at
Cái này để làm gì? Nếu không dùng xóa đi

2019-04-01 07:47 UTC, N-Viet-ruby-dev commented on db/migrate/20190401071857_create_users.rb
> +      t.boolean :admin
Sử dụng biến integer role để xác định admin

2019-04-01 07:47 UTC, N-Viet-ruby-dev commented on db/migrate/20190401071857_create_users.rb
> +      t.string :encrypted_password
Cái này để làm gì? Nếu không dùng xóa đi

2019-04-01 07:47 UTC, N-Viet-ruby-dev commented on db/migrate/20190401071857_create_users.rb
> +      t.string :provider
Cái này để làm gì? Nếu không dùng xóa đi

2019-04-01 07:47 UTC, N-Viet-ruby-dev commented on db/migrate/20190401071857_create_users.rb
> +      t.string :uid
Cái này để làm gì? Nếu không dùng xóa đi

2019-04-01 07:47 UTC, N-Viet-ruby-dev commented on app/models/user.rb
> +class User < ApplicationRecord
Thêm validate cho các trường trong user

2019-04-01 08:09 UTC, manh11117 commented on db/migrate/20190401071857_create_users.rb
> +      t.string :reset_password_token, index: true, name: "index_users_on_reset_password_token", unique: true
trường này để reset password sau này có dùng anh ạ

2019-04-01 08:35 UTC, manh11117 commented on test/fixtures/users.yml
> +# Read about fixtures at http://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
em xóa hết file test rồi, còn thư mục để nguyên

2019-04-01 08:36 UTC, manh11117 commented on db/migrate/20190401071857_create_users.rb
> +      t.string :reset_password_token, index: true, name: "index_users_on_reset_password_token", unique: true
mấy cái này của devise sau này dùng hết anh ạ

2019-04-01 08:36 UTC, manh11117 commented on db/migrate/20190401071857_create_users.rb
> +      t.datetime :reset_password_sent_at
mấy cái này của devise sau này dùng hết anh ạ

2019-04-01 08:36 UTC, manh11117 commented on db/migrate/20190401071857_create_users.rb
> +      t.datetime :remember_created_at
mấy cái này của devise sau này dùng hết anh ạ

2019-04-01 08:37 UTC, manh11117 commented on db/migrate/20190401071857_create_users.rb
> +      t.boolean :admin
em thay string:admin bằng string:role rồi

2019-04-01 08:38 UTC, manh11117 commented on db/migrate/20190401071857_create_users.rb
> +      t.string :encrypted_password
trường này để lưu phiên bản mã hóa của phần mềm anh ạ

2019-04-01 08:40 UTC, manh11117 commented on db/migrate/20190401071857_create_users.rb
> +      t.string :provider
cái này để lưu nhà cung cấp như facebook, google khi người dùng đăng nhập qua các nhà cung cấp này

2019-04-01 08:42 UTC, manh11117 commented on db/migrate/20190401071857_create_users.rb
> +      t.string :uid
mấy cái này của devise sau này dùng hết anh ạ

2019-04-01 11:47 UTC, N-Viet-ruby-dev commented on db/migrate/20190401071857_create_users.rb
> +      t.string :encrypted_password
OK

2019-04-01 11:47 UTC, N-Viet-ruby-dev commented on db/migrate/20190401071857_create_users.rb
> +      t.string :reset_password_token, index: true, name: "index_users_on_reset_password_token", unique: true
Khi nào cần sẽ add vào sau

2019-04-01 11:47 UTC, N-Viet-ruby-dev commented on db/migrate/20190401071857_create_users.rb
> +      t.datetime :reset_password_sent_at
Khi nào cần sẽ add vào sau

2019-04-01 11:47 UTC, N-Viet-ruby-dev commented on db/migrate/20190401071857_create_users.rb
> +      t.datetime :remember_created_at
Khi nào cần sẽ add vào sau

2019-04-01 11:47 UTC, N-Viet-ruby-dev commented on db/migrate/20190401071857_create_users.rb
> +      t.string :provider
Hiện tại không cần trường này

2019-04-01 11:47 UTC, N-Viet-ruby-dev commented on db/migrate/20190401071857_create_users.rb
> +      t.string :uid
Khi nào cần sẽ add vào sau

2019-04-01 11:48 UTC, N-Viet-ruby-dev commented on db/migrate/20190401071857_create_users.rb
> +      t.string :role
Dùng integer, setup enum cho role trong model

2019-04-01 11:52 UTC, N-Viet-ruby-dev commented on db/migrate/20190401071857_create_users.rb
> +      t.string :encrypted_password
Cài đặt trường password theo tutorial
https://www.railstutorial.org/book/modeling_users#sec-adding_a_secure_password

2019-04-02 11:12 UTC, manh11117 commented
![image](https://user-images.githubusercontent.com/48306716/55398492-e057e480-5572-11e9-95f1-750bfdeec147.png)

2019-04-02 11:19 UTC, N-Viet-ruby-dev requested changes

2019-04-02 11:19 UTC, N-Viet-ruby-dev commented on app/controllers/home_controller.rb
> +# frozen_string_literal: true
Hiện Không cần file này, khi nào cần thì thêm vào sau

2019-04-02 11:19 UTC, N-Viet-ruby-dev commented on app/controllers/users_controller.rb
> +# frozen_string_literal: true
Hiện Không cần file này, khi nào cần thì thêm vào sau

2019-04-02 11:19 UTC, N-Viet-ruby-dev commented on app/views/home/home.html.erb
> +<h1>Xin chào, Rails!</h1>
Hiện Không cần file này, khi nào cần thì thêm vào sau

2019-04-02 11:19 UTC, N-Viet-ruby-dev commented on app/views/users/new.html.erb
> +<h1>Users#new</h1>
Hiện Không cần file này, khi nào cần thì thêm vào sau

2019-04-02 11:19 UTC, N-Viet-ruby-dev commented on config/routes.rb
> +  root "home#index"
Chưa cần phải setting ở routes

2019-04-02 11:19 UTC, N-Viet-ruby-dev commented on db/migrate/20190402105855_add_index_to_users_email.rb
> +class AddIndexToUsersEmail < ActiveRecord::Migration[5.2]
File này không thay đổi gì cả, xóa đi

2019-04-02 11:19 UTC, N-Viet-ruby-dev commented on db/migrate/20190402105926_add_password_digest_to_users.rb
> +    add_column :users, :password_digest, :string
Ghép vào chung với migration tạo bảng

2019-04-02 11:19 UTC, N-Viet-ruby-dev commented on db/migrate/20190402061112_create_users.rb
> +      t.string :email
Trường role đâu rồi

2019-04-02 11:19 UTC, N-Viet-ruby-dev commented on app/models/user.rb
> +  has_secure_password
đưa dòng này lên trên khối validates

2019-04-02 11:44 UTC, manh11117 commented on db/migrate/20190402061112_create_users.rb
> +      t.string :email
fixed

2019-04-03 01:03 UTC, N-Viet-ruby-dev approved these changes

2019-04-03 01:03 UTC, merged