ticket9698 : Create form for create/update users
N-Viet-ruby-dev/question-answer-v2 pull request #5
Opened 2019-04-08 10:12 UTC by manh11117

change gem byebug by spy

2019-04-08 10:25 UTC, luongvietdung commented on app/controllers/admin/users_controller.rb
> +        render "new"
dung symbol

2019-04-08 10:26 UTC, luongvietdung commented on app/controllers/admin/users_controller.rb
> +        render "edit"
dung symbol

2019-04-08 10:27 UTC, luongvietdung commented on app/views/admin/users/edit.html.erb
> +<%= link_to 'Trở lại', admin_users_path %>
Dung tieng anh

2019-04-08 10:28 UTC, luongvietdung commented on app/controllers/admin/users_controller.rb
> +      @user = User.find(params[:id])
Chuyển vào `before_action`

2019-04-08 10:29 UTC, luongvietdung commented on app/views/admin/users/new.html.erb
> +
Thừa dòng trống

2019-04-08 11:02 UTC, luongvietdung commented on app/controllers/admin/users_controller.rb
> +    before_action :find_user, only: %i[edit update destroy]
remove `destroy`

2019-04-08 11:07 UTC, luongvietdung commented on app/views/admin/users/_form.html.erb
> +  <%= form.submit "Create User", class: "btn btn-primary"%>
Dùng biến truyền vào từ partial form

2019-04-08 11:12 UTC, luongvietdung reviewed
![Ruby on Rails Question Answer](https://user-images.githubusercontent.com/13132796/55719906-987d0580-5a29-11e9-956e-9898534574d1.png)
Trong forrm edit, nếu không edit password sẽ bị báo lỗi

2019-04-08 11:14 UTC, luongvietdung requested changes
Email của user không được trùng nhau

2019-04-08 11:44 UTC, manh11117 commented on app/views/admin/users/new.html.erb
> +
edited

2019-04-08 11:44 UTC, manh11117 commented on app/views/admin/users/_form.html.erb
> +  <%= form.submit "Create User", class: "btn btn-primary"%>
complete

2019-04-08 11:44 UTC, manh11117 commented on app/controllers/admin/users_controller.rb
> +    before_action :find_user, only: %i[edit update destroy]
complete

2019-04-08 11:44 UTC, manh11117 commented on app/views/admin/users/new.html.erb
> +
complete

2019-04-08 11:45 UTC, manh11117 commented on app/controllers/admin/users_controller.rb
> +      @user = User.find(params[:id])
complete

2019-04-08 11:45 UTC, manh11117 commented on app/views/admin/users/edit.html.erb
> +<%= link_to 'Trở lại', admin_users_path %>
complete

2019-04-08 11:45 UTC, manh11117 commented on app/controllers/admin/users_controller.rb
> +        render "edit"
complete

2019-04-08 11:45 UTC, manh11117 commented on app/controllers/admin/users_controller.rb
> +        render "new"
complete

2019-04-08 11:53 UTC, manh11117 commented
complete add , uniqueness: {case_sensitive: false}

2019-04-09 03:16 UTC, N-Viet-ruby-dev commented on app/views/admin/users/edit.html.erb
> +  <%= form.select(:role, User.roles.keys.map { |w| [w.humanize, w] }, {:include_blank => "Select"}, {:class => "form-control"} ) %>
Sửa lại cách viết hash

2019-04-09 03:58 UTC, manh11117 commented on app/views/admin/users/edit.html.erb
> +  <%= form.select(:role, User.roles.keys.map { |w| [w.humanize, w] }, {:include_blank => "Select"}, {:class => "form-control"} ) %>
complete

2019-04-09 04:13 UTC, N-Viet-ruby-dev commented on app/views/admin/users/edit.html.erb
> +<div class="col-md-6 col-md-offset-3">
div này là con của div phía trên, thụt vào một indent

2019-04-09 04:14 UTC, N-Viet-ruby-dev commented on app/views/admin/users/edit.html.erb
> +<%= form_with model: [:admin, @user] , local: true do |form| %>
form này là con của div phía trên, thụt vào một indent, tương tự với file new.html.erb

2019-04-09 04:15 UTC, N-Viet-ruby-dev commented on app/views/admin/users/edit.html.erb
> +  <% if @user.errors.any? %>
Phần này giống hệt với file new.html.erb, viết vào một partial dùng chung

2019-04-09 06:59 UTC, manh11117 commented on app/views/admin/users/edit.html.erb
> +<%= form_with model: [:admin, @user] , local: true do |form| %>
complete

2019-04-09 07:33 UTC, N-Viet-ruby-dev commented on app/views/admin/users/_form.html.erb
> +      <% params.each do | key,value | %>
tại sao lại viết như thế này?

2019-04-09 07:52 UTC, N-Viet-ruby-dev commented on app/views/admin/users/_form.html.erb
> +      <% params.each do |key, value| %>
tại sao lại viết khối code này?

2019-04-09 07:53 UTC, N-Viet-ruby-dev commented on app/views/admin/users/_form.html.erb
> +</div>
Thẻ đóng căn ngang hàng với thẻ mở

2019-04-09 09:03 UTC, N-Viet-ruby-dev commented
![Screenshot from 2019-04-09 16-02-25](https://user-images.githubusercontent.com/37279359/55787638-f15ba500-5ae0-11e9-8ad2-1adb92d85262.png)
- Không có password_confirmation
- Lỗi 'Password can't be blank' bị ghi hai lần

2019-04-09 11:00 UTC, N-Viet-ruby-dev approved these changes
LGTM

2019-04-09 11:00 UTC, merged